name: Plugin Size and Asset Audit

on:
  pull_request:
    branches:
      - 'main'
      - 'develop'

env:
  MAX_SIZE_INCREASE_PERCENT: 10
  MAX_IMAGE_SIZE_KB: 500
  MAX_PHP_SIZE_INCREASE_PERCENT: 15

jobs:
  size-audit:
    name: Audit Plugin Size and Assets
    runs-on: ubuntu-latest
    permissions: {
      contents: read,
      pull-requests: write
    }
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@bf6b4fbd49ca58e4608c9c89fba0b8d90bd2a39f  # v2.35.5
        with:
          php-version: '8.1'
          coverage: none
          tools: composer, cs2pr

      - name: Setup workflow context
        id: workflow
        working-directory: ${{ runner.temp }}
        env:
          REPO: ${{ github.repository }}
          PLUGIN_NAME: ${{ vars.PLUGIN_NAME }}
        run: |
          mkdir dist
          echo "DIST=${PWD}/dist" >> "$GITHUB_OUTPUT"
          echo "PACKAGE=$PLUGIN_NAME" >> "$GITHUB_OUTPUT"

      - name: Use Node.js 20.x
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444  # v5.0.0
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Cache Composer vendor directory
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830  # v4.3.0
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Show versions
        run: |
          php --version
          composer --version
          node --version
          npm --version

      - name: Install PHP Dependencies
        run: composer install --no-progress --no-dev --optimize-autoloader --prefer-dist

      - name: NPM Install
        run: npm install --legacy-peer-deps

      - name: Build JavaScript
        run: npm run build

      - name: Prepare files
        env:
          DIST: ${{ steps.workflow.outputs.DIST }}
        run: rsync -r --include-from=.distinclude --exclude-from=.distignore . "$DIST"

      - name: Calculate Total Plugin Size
        id: plugin_size
        run: |
          TOTAL_SIZE_BYTES=$(du -sb "${{ steps.workflow.outputs.DIST }}" | cut -f1)
          TOTAL_SIZE_HUMAN=$(numfmt --to=iec --suffix=B "${TOTAL_SIZE_BYTES}")
          {
            echo "total_size_bytes=${TOTAL_SIZE_BYTES}"
            echo "total_size_human=${TOTAL_SIZE_HUMAN}"
          } >> "${GITHUB_OUTPUT}"

      # -------------------------------------------------------
      # Calculate Total plugin size from the base branch for comparison
      # -------------------------------------------------------
      - name: Checkout Base Branch
        if: github.event_name == 'pull_request'
        id: get_base_sha
        run: |
          # El SHA del último commit de la rama destino (e.g., 'main')
          BASE_SHA=${{ github.event.pull_request.base.sha }}
          echo "BASE_SHA=$BASE_SHA" >> $GITHUB_OUTPUT
          echo "change to SHA: $BASE_SHA"
      - name: Clean Working Directory (Prevent Stash/Commit Error)
        run: |
          # Discard all changes in tracked files
          git reset --hard HEAD
          # Remove untracked files and directories (-d) with force (-f)
          git clean -df
          echo "Working directory cleaned." 
      - name: Checkout a la Rama Base
        run: |
          git checkout ${{ steps.get_base_sha.outputs.BASE_SHA }}
          echo "Listo. Nos encontramos en la rama: $(git branch --show-current)"

      - name: Setup workflow context for Base Branch
        id: workflow-base
        working-directory: ${{ runner.temp }}
        env:
          REPO: ${{ github.repository }}
          PLUGIN_NAME: ${{ vars.PLUGIN_NAME }}
        run: |
          mkdir dist_base
          echo "DIST=${PWD}/dist_base" >> "$GITHUB_OUTPUT"
          echo "PACKAGE=$PLUGIN_NAME" >> "$GITHUB_OUTPUT"
      - name: Prepare files for Base Branch
        env:
          DIST: ${{ steps.workflow-base.outputs.DIST }}
        run: rsync -r --include-from=.distinclude --exclude-from=.distignore . "$DIST"  
      - name: Calculate Total Plugin Size for Base Branch
        id: base_plugin_size
        run: |
          TOTAL_SIZE_BYTES=$(du -sb "${{ steps.workflow-base.outputs.DIST }}" | cut -f1)
          TOTAL_SIZE_HUMAN=$(numfmt --to=iec --suffix=B "${TOTAL_SIZE_BYTES}")
          {
            echo "base_total_size_bytes=${TOTAL_SIZE_BYTES}"
            echo "base_total_size_human=${TOTAL_SIZE_HUMAN}"
          } >> "${GITHUB_OUTPUT}" 
          
      - name: Compare Plugin Sizes
        if: github.event_name == 'pull_request'
        env:
          CURRENT_SIZE_BYTES: ${{ steps.plugin_size.outputs.total_size_bytes }}
          BASE_SIZE_BYTES: ${{ steps.base_plugin_size.outputs.base_total_size_bytes }}
          MAX_INCREASE_PERCENT: ${{ env.MAX_SIZE_INCREASE_PERCENT }}
        run: |
          SIZE_DIFF=$((CURRENT_SIZE_BYTES - BASE_SIZE_BYTES))
          if [ $BASE_SIZE_BYTES -eq 0 ]; then
            PERCENT_INCREASE=0
          else
            PERCENT_INCREASE=$((SIZE_DIFF * 100 / BASE_SIZE_BYTES))
          fi
          echo "Size Difference (Bytes): $SIZE_DIFF"
          echo "Percentage Increase: $PERCENT_INCREASE%"
          if [ $PERCENT_INCREASE -gt $MAX_INCREASE_PERCENT ]; then
            echo "Error: Plugin size increased by $PERCENT_INCREASE%, which exceeds the maximum allowed increase of $MAX_INCREASE_PERCENT%."
            exit 1
          fi  

      - name: Generate Size Audit Repository
        env:
            TOTAL_SIZE_HUMAN: ${{ steps.plugin_size.outputs.total_size_human }}
            PERCENT_INCREASE: ${{ steps.compare_plugin_sizes.outputs.PERCENT_INCREASE }}
            BASE_TOTAL_SIZE_HUMAN: ${{ steps.base_plugin_size.outputs.base_total_size_human }}
            
        run: |
            REPORT="final-report.md"
            {
              echo "## Plugin Size Audit Report"
              echo
              echo "### Total Plugin Size"
              echo "- Current Size: ${TOTAL_SIZE_HUMAN}"
              echo "- Base Size: ${BASE_TOTAL_SIZE_HUMAN}"
              echo "- Percentage Increase: ${PERCENT_INCREASE}%"
            } > "${REPORT}"
      - name: Comment PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('final-report.md', 'utf8');

            // Check if we already have a comment from this workflow
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const existingComment = comments.data.find(comment =>
              comment.user.type === 'Bot' &&
              comment.body.includes('## Plugin Size Audit Report')
            );

            if (existingComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: report
              });
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: report
              });
            }

      
